// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	resources "github.com/wspowell/snailmail/resources"
)

// MailStore is an autogenerated mock type for the MailStore type
type MailStore struct {
	mock.Mock
}

// CollectMail provides a mock function with given fields: mailboxId
func (_m *MailStore) CollectMail(mailboxId uint32) ([]uint32, error) {
	ret := _m.Called(mailboxId)

	var r0 []uint32
	if rf, ok := ret.Get(0).(func(uint32) []uint32); ok {
		r0 = rf(mailboxId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint32)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = rf(mailboxId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMail provides a mock function with given fields: mail
func (_m *MailStore) CreateMail(mail resources.Mail) (uint32, error) {
	ret := _m.Called(mail)

	var r0 uint32
	if rf, ok := ret.Get(0).(func(resources.Mail) uint32); ok {
		r0 = rf(mail)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(resources.Mail) error); ok {
		r1 = rf(mail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepositMail provides a mock function with given fields: mailId, mailboxId
func (_m *MailStore) DepositMail(mailId uint32, mailboxId uint32) error {
	ret := _m.Called(mailId, mailboxId)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint32, uint32) error); ok {
		r0 = rf(mailId, mailboxId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadMail provides a mock function with given fields: mailId
func (_m *MailStore) ReadMail(mailId uint32) (*resources.Mail, error) {
	ret := _m.Called(mailId)

	var r0 *resources.Mail
	if rf, ok := ret.Get(0).(func(uint32) *resources.Mail); ok {
		r0 = rf(mailId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.Mail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = rf(mailId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrackMail provides a mock function with given fields: mailId
func (_m *MailStore) TrackMail(mailId uint32) error {
	ret := _m.Called(mailId)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint32) error); ok {
		r0 = rf(mailId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
