AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  UsersCreate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /users
            Method: post